stages:
    - image
    - build
    - test

variables:
    GIT_SUBMODULE_STRATEGY: "none"

include:
    - local: "scripts/ci/image.yml"
    - local: "scripts/ci/build.yml"
    - local: "scripts/ci/test.yml"
